Fix Linux-x32 and pure 32-bit build.
Fixes:

expect.c: In function ‘zif_expect_expectl’:
expect.c:354:62: error: passing argument 3 of ‘zend_hash_get_current_key’ from incompatible pointer type [-Wincompatible-pointer-types]
354 | zend_hash_get_current_key(Z_ARRVAL_P(z_cases), NULL, &key);
| ^~~~
| |
| ulong * {aka long unsigned int *}
[...]
In file included from /usr/include/php/Zend/zend.h:33,
/usr/include/php/Zend/zend_hash.h:275:130: note: expected ‘zend_ulong *’ {aka ‘unsigned int *’} but argument is of type ‘ulong *’ {aka ‘long unsigned int *’}
275 | static zend_always_inline zend_hash_key_type zend_hash_get_current_key(const HashTable *ht, zend_string **str_index, zend_ulong *num_index) {